/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeIndexRouteImport } from './routes/_authenticated/me/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedMeVehicleLogRouteImport } from './routes/_authenticated/me/vehicle-log'
import { Route as AuthenticatedMeReportsRouteImport } from './routes/_authenticated/me/reports'
import { Route as AuthenticatedMeProfileRouteImport } from './routes/_authenticated/me/profile'
import { Route as AuthenticatedMeNotificationsRouteImport } from './routes/_authenticated/me/notifications'
import { Route as AuthenticatedMeLeaveRouteImport } from './routes/_authenticated/me/leave'
import { Route as AuthenticatedMeAttendanceRouteImport } from './routes/_authenticated/me/attendance'
import { Route as AuthenticatedAdminVehicleLogsRouteImport } from './routes/_authenticated/admin/vehicle-logs'
import { Route as AuthenticatedAdminUpdatesRouteImport } from './routes/_authenticated/admin/updates'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin/tasks'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/admin/locations'
import { Route as AuthenticatedAdminLeavesRouteImport } from './routes/_authenticated/admin/leaves'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin/employees'
import { Route as AuthenticatedAdminDailyReportsRouteImport } from './routes/_authenticated/admin/daily-reports'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedMeTasksIndexRouteImport } from './routes/_authenticated/me/tasks/index'
import { Route as ApiPublicHooksCleanupMeterPhotosRouteImport } from './routes/api/public/hooks/cleanup-meter-photos'
import { Route as ApiPublicHooksCleanupAttendancePhotosRouteImport } from './routes/api/public/hooks/cleanup-attendance-photos'
import { Route as AuthenticatedMeTasksIdRouteImport } from './routes/_authenticated/me/tasks/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeIndexRoute = AuthenticatedMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeVehicleLogRoute =
  AuthenticatedMeVehicleLogRouteImport.update({
    id: '/me/vehicle-log',
    path: '/me/vehicle-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeReportsRoute = AuthenticatedMeReportsRouteImport.update({
  id: '/me/reports',
  path: '/me/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeProfileRoute = AuthenticatedMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeNotificationsRoute =
  AuthenticatedMeNotificationsRouteImport.update({
    id: '/me/notifications',
    path: '/me/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeLeaveRoute = AuthenticatedMeLeaveRouteImport.update({
  id: '/me/leave',
  path: '/me/leave',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeAttendanceRoute =
  AuthenticatedMeAttendanceRouteImport.update({
    id: '/me/attendance',
    path: '/me/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVehicleLogsRoute =
  AuthenticatedAdminVehicleLogsRouteImport.update({
    id: '/admin/vehicle-logs',
    path: '/admin/vehicle-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUpdatesRoute =
  AuthenticatedAdminUpdatesRouteImport.update({
    id: '/admin/updates',
    path: '/admin/updates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/admin/locations',
    path: '/admin/locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeavesRoute =
  AuthenticatedAdminLeavesRouteImport.update({
    id: '/admin/leaves',
    path: '/admin/leaves',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDailyReportsRoute =
  AuthenticatedAdminDailyReportsRouteImport.update({
    id: '/admin/daily-reports',
    path: '/admin/daily-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/admin/attendance',
    path: '/admin/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeTasksIndexRoute =
  AuthenticatedMeTasksIndexRouteImport.update({
    id: '/me/tasks/',
    path: '/me/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksCleanupMeterPhotosRoute =
  ApiPublicHooksCleanupMeterPhotosRouteImport.update({
    id: '/api/public/hooks/cleanup-meter-photos',
    path: '/api/public/hooks/cleanup-meter-photos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupAttendancePhotosRoute =
  ApiPublicHooksCleanupAttendancePhotosRouteImport.update({
    id: '/api/public/hooks/cleanup-attendance-photos',
    path: '/api/public/hooks/cleanup-attendance-photos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMeTasksIdRoute = AuthenticatedMeTasksIdRouteImport.update({
  id: '/me/tasks/$id',
  path: '/me/tasks/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/daily-reports': typeof AuthenticatedAdminDailyReportsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/updates': typeof AuthenticatedAdminUpdatesRoute
  '/admin/vehicle-logs': typeof AuthenticatedAdminVehicleLogsRoute
  '/me/attendance': typeof AuthenticatedMeAttendanceRoute
  '/me/leave': typeof AuthenticatedMeLeaveRoute
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/reports': typeof AuthenticatedMeReportsRoute
  '/me/vehicle-log': typeof AuthenticatedMeVehicleLogRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/me/': typeof AuthenticatedMeIndexRoute
  '/me/tasks/$id': typeof AuthenticatedMeTasksIdRoute
  '/api/public/hooks/cleanup-attendance-photos': typeof ApiPublicHooksCleanupAttendancePhotosRoute
  '/api/public/hooks/cleanup-meter-photos': typeof ApiPublicHooksCleanupMeterPhotosRoute
  '/me/tasks/': typeof AuthenticatedMeTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/daily-reports': typeof AuthenticatedAdminDailyReportsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/updates': typeof AuthenticatedAdminUpdatesRoute
  '/admin/vehicle-logs': typeof AuthenticatedAdminVehicleLogsRoute
  '/me/attendance': typeof AuthenticatedMeAttendanceRoute
  '/me/leave': typeof AuthenticatedMeLeaveRoute
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/reports': typeof AuthenticatedMeReportsRoute
  '/me/vehicle-log': typeof AuthenticatedMeVehicleLogRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/me': typeof AuthenticatedMeIndexRoute
  '/me/tasks/$id': typeof AuthenticatedMeTasksIdRoute
  '/api/public/hooks/cleanup-attendance-photos': typeof ApiPublicHooksCleanupAttendancePhotosRoute
  '/api/public/hooks/cleanup-meter-photos': typeof ApiPublicHooksCleanupMeterPhotosRoute
  '/me/tasks': typeof AuthenticatedMeTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/daily-reports': typeof AuthenticatedAdminDailyReportsRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/leaves': typeof AuthenticatedAdminLeavesRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/updates': typeof AuthenticatedAdminUpdatesRoute
  '/_authenticated/admin/vehicle-logs': typeof AuthenticatedAdminVehicleLogsRoute
  '/_authenticated/me/attendance': typeof AuthenticatedMeAttendanceRoute
  '/_authenticated/me/leave': typeof AuthenticatedMeLeaveRoute
  '/_authenticated/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/_authenticated/me/profile': typeof AuthenticatedMeProfileRoute
  '/_authenticated/me/reports': typeof AuthenticatedMeReportsRoute
  '/_authenticated/me/vehicle-log': typeof AuthenticatedMeVehicleLogRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/me/': typeof AuthenticatedMeIndexRoute
  '/_authenticated/me/tasks/$id': typeof AuthenticatedMeTasksIdRoute
  '/api/public/hooks/cleanup-attendance-photos': typeof ApiPublicHooksCleanupAttendancePhotosRoute
  '/api/public/hooks/cleanup-meter-photos': typeof ApiPublicHooksCleanupMeterPhotosRoute
  '/_authenticated/me/tasks/': typeof AuthenticatedMeTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/daily-reports'
    | '/admin/employees'
    | '/admin/leaves'
    | '/admin/locations'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/updates'
    | '/admin/vehicle-logs'
    | '/me/attendance'
    | '/me/leave'
    | '/me/notifications'
    | '/me/profile'
    | '/me/reports'
    | '/me/vehicle-log'
    | '/admin/'
    | '/me/'
    | '/me/tasks/$id'
    | '/api/public/hooks/cleanup-attendance-photos'
    | '/api/public/hooks/cleanup-meter-photos'
    | '/me/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/daily-reports'
    | '/admin/employees'
    | '/admin/leaves'
    | '/admin/locations'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/updates'
    | '/admin/vehicle-logs'
    | '/me/attendance'
    | '/me/leave'
    | '/me/notifications'
    | '/me/profile'
    | '/me/reports'
    | '/me/vehicle-log'
    | '/admin'
    | '/me'
    | '/me/tasks/$id'
    | '/api/public/hooks/cleanup-attendance-photos'
    | '/api/public/hooks/cleanup-meter-photos'
    | '/me/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/daily-reports'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/leaves'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/updates'
    | '/_authenticated/admin/vehicle-logs'
    | '/_authenticated/me/attendance'
    | '/_authenticated/me/leave'
    | '/_authenticated/me/notifications'
    | '/_authenticated/me/profile'
    | '/_authenticated/me/reports'
    | '/_authenticated/me/vehicle-log'
    | '/_authenticated/admin/'
    | '/_authenticated/me/'
    | '/_authenticated/me/tasks/$id'
    | '/api/public/hooks/cleanup-attendance-photos'
    | '/api/public/hooks/cleanup-meter-photos'
    | '/_authenticated/me/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksCleanupAttendancePhotosRoute: typeof ApiPublicHooksCleanupAttendancePhotosRoute
  ApiPublicHooksCleanupMeterPhotosRoute: typeof ApiPublicHooksCleanupMeterPhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me/': {
      id: '/_authenticated/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AuthenticatedMeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/vehicle-log': {
      id: '/_authenticated/me/vehicle-log'
      path: '/me/vehicle-log'
      fullPath: '/me/vehicle-log'
      preLoaderRoute: typeof AuthenticatedMeVehicleLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/reports': {
      id: '/_authenticated/me/reports'
      path: '/me/reports'
      fullPath: '/me/reports'
      preLoaderRoute: typeof AuthenticatedMeReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/profile': {
      id: '/_authenticated/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof AuthenticatedMeProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/notifications': {
      id: '/_authenticated/me/notifications'
      path: '/me/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof AuthenticatedMeNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/leave': {
      id: '/_authenticated/me/leave'
      path: '/me/leave'
      fullPath: '/me/leave'
      preLoaderRoute: typeof AuthenticatedMeLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/attendance': {
      id: '/_authenticated/me/attendance'
      path: '/me/attendance'
      fullPath: '/me/attendance'
      preLoaderRoute: typeof AuthenticatedMeAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vehicle-logs': {
      id: '/_authenticated/admin/vehicle-logs'
      path: '/admin/vehicle-logs'
      fullPath: '/admin/vehicle-logs'
      preLoaderRoute: typeof AuthenticatedAdminVehicleLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/updates': {
      id: '/_authenticated/admin/updates'
      path: '/admin/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AuthenticatedAdminUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leaves': {
      id: '/_authenticated/admin/leaves'
      path: '/admin/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AuthenticatedAdminLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/daily-reports': {
      id: '/_authenticated/admin/daily-reports'
      path: '/admin/daily-reports'
      fullPath: '/admin/daily-reports'
      preLoaderRoute: typeof AuthenticatedAdminDailyReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/tasks/': {
      id: '/_authenticated/me/tasks/'
      path: '/me/tasks'
      fullPath: '/me/tasks/'
      preLoaderRoute: typeof AuthenticatedMeTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/cleanup-meter-photos': {
      id: '/api/public/hooks/cleanup-meter-photos'
      path: '/api/public/hooks/cleanup-meter-photos'
      fullPath: '/api/public/hooks/cleanup-meter-photos'
      preLoaderRoute: typeof ApiPublicHooksCleanupMeterPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-attendance-photos': {
      id: '/api/public/hooks/cleanup-attendance-photos'
      path: '/api/public/hooks/cleanup-attendance-photos'
      fullPath: '/api/public/hooks/cleanup-attendance-photos'
      preLoaderRoute: typeof ApiPublicHooksCleanupAttendancePhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me/tasks/$id': {
      id: '/_authenticated/me/tasks/$id'
      path: '/me/tasks/$id'
      fullPath: '/me/tasks/$id'
      preLoaderRoute: typeof AuthenticatedMeTasksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminDailyReportsRoute: typeof AuthenticatedAdminDailyReportsRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminLeavesRoute: typeof AuthenticatedAdminLeavesRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminUpdatesRoute: typeof AuthenticatedAdminUpdatesRoute
  AuthenticatedAdminVehicleLogsRoute: typeof AuthenticatedAdminVehicleLogsRoute
  AuthenticatedMeAttendanceRoute: typeof AuthenticatedMeAttendanceRoute
  AuthenticatedMeLeaveRoute: typeof AuthenticatedMeLeaveRoute
  AuthenticatedMeNotificationsRoute: typeof AuthenticatedMeNotificationsRoute
  AuthenticatedMeProfileRoute: typeof AuthenticatedMeProfileRoute
  AuthenticatedMeReportsRoute: typeof AuthenticatedMeReportsRoute
  AuthenticatedMeVehicleLogRoute: typeof AuthenticatedMeVehicleLogRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMeIndexRoute: typeof AuthenticatedMeIndexRoute
  AuthenticatedMeTasksIdRoute: typeof AuthenticatedMeTasksIdRoute
  AuthenticatedMeTasksIndexRoute: typeof AuthenticatedMeTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminDailyReportsRoute: AuthenticatedAdminDailyReportsRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminLeavesRoute: AuthenticatedAdminLeavesRoute,
  AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
  AuthenticatedAdminUpdatesRoute: AuthenticatedAdminUpdatesRoute,
  AuthenticatedAdminVehicleLogsRoute: AuthenticatedAdminVehicleLogsRoute,
  AuthenticatedMeAttendanceRoute: AuthenticatedMeAttendanceRoute,
  AuthenticatedMeLeaveRoute: AuthenticatedMeLeaveRoute,
  AuthenticatedMeNotificationsRoute: AuthenticatedMeNotificationsRoute,
  AuthenticatedMeProfileRoute: AuthenticatedMeProfileRoute,
  AuthenticatedMeReportsRoute: AuthenticatedMeReportsRoute,
  AuthenticatedMeVehicleLogRoute: AuthenticatedMeVehicleLogRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMeIndexRoute: AuthenticatedMeIndexRoute,
  AuthenticatedMeTasksIdRoute: AuthenticatedMeTasksIdRoute,
  AuthenticatedMeTasksIndexRoute: AuthenticatedMeTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksCleanupAttendancePhotosRoute:
    ApiPublicHooksCleanupAttendancePhotosRoute,
  ApiPublicHooksCleanupMeterPhotosRoute: ApiPublicHooksCleanupMeterPhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
